schema_version = "1.0.0"
id = "reference_scale"
version = "1.6.0"
name = "Reference Scale"
tagline = "Spawn 2D scale references via point-and-click"
maintainer = "Your Name <your@email.com>"
type = "add-on"
url = "https://extensions.blender.org"
blender_version_min = "4.2.0"
license = [
    "SPDX:GPL-3.0-or-later"
]